[WIP]Android_profile
jphacks/KB_1809 pull request #81
Opened 2018-10-29 06:03 UTC by lanqiugit

2018-10-29 06:07 UTC, lanqiugit commented
![screenshot_1540793231](https://user-images.githubusercontent.com/35892183/47632160-5606f100-db8c-11e8-809b-077808a701e7.png)

2018-10-30 13:26 UTC, lanqiugit commented
![screenshot_1540905934](https://user-images.githubusercontent.com/35892183/47721169-e0397d00-dc92-11e8-85bb-11df2f207d02.png)
![screenshot_1540905963](https://user-images.githubusercontent.com/35892183/47721174-e3cd0400-dc92-11e8-80d5-937dfafab824.png)
![screenshot_1540905945](https://user-images.githubusercontent.com/35892183/47721177-e62f5e00-dc92-11e8-99e0-ad945adcad47.png)

2018-10-30 13:28 UTC, lanqiugit commented
recyclerviewのアイテムのレイアウトをまだ変更してませんでした.
修正します.

2018-10-31 12:56 UTC, ken-kentan commented
アイコンが + になってるのは？

2018-10-31 13:03 UTC, lanqiugit commented
仮の画像を入れたままにしていました.
ユーザーの画像が入る予定です.

2018-10-31 14:50 UTC, ken-kentan commented
仮の画像は item_plan.xml を参考にしてください

2018-11-02 11:13 UTC, lanqiugit commented
![screenshot_1541157092](https://user-images.githubusercontent.com/35892183/47912328-97283980-dedb-11e8-8e22-0743302a97d0.png)
ユーザ情報が表示できるようになりました.
ユーザが投稿したプランのアイテム一覧をこれから修正します.

2018-11-03 03:39 UTC, lanqiugit commented
![screenshot_1541216076](https://user-images.githubusercontent.com/35892183/47947731-5543d580-df65-11e8-8ea3-fa93268ab72b.png)
![screenshot_1541216082](https://user-images.githubusercontent.com/35892183/47947732-5543d580-df65-11e8-8450-388d3028f7f8.png)
![screenshot_1541216094](https://user-images.githubusercontent.com/35892183/47947733-55dc6c00-df65-11e8-994c-91ba5383094e.png)
プロフィール画面全体が完成しました.
問題なければ, マージしてもらって大丈夫です.

2018-11-03 10:43 UTC, ken-kentan commented
ビルドが失敗してるので直してください。

2018-11-03 10:45 UTC, ken-kentan requested changes
API v2を使用してください。

2018-11-04 05:47 UTC, lanqiugit commented
![screenshot_1541310195](https://user-images.githubusercontent.com/35892183/47960467-6e6d8480-e040-11e8-9672-6319520d4575.png)
![screenshot_1541310201](https://user-images.githubusercontent.com/35892183/47960468-6e6d8480-e040-11e8-91da-f12961cc0206.png)
API V2に対応しました.
問題なければ, マージしていただいて大丈夫です.

2018-11-04 09:31 UTC, ken-kentan commented
気になったとこを修正していきます。

2018-11-04 13:05 UTC, merged